services:
  local-dev:
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    container_name: jury-dao
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    image: mysql
    ports:
      - '3309:3306'
