### Health
GET http://localhost:8010/

### Auth(Login)
POST http://localhost:8010/auth
Content-Type: application/json

{
  "walletAddress": "0x714Ca817Ad92f9bae05DC18fA5312eB3F480cCCB"
}


### Create a jury
POST http://localhost:8010/juries
Content-Type: application/json

{
  "plaintiffId": 1,
  "plaintiffTitle": "test1",
  "plaintiffContent": "test1test1",
  "defendantId": 2
}


### Get juries
GET http://localhost:8010/juries?page=10&size=200

### Get a jury
GET http://localhost:8010/juries/2

### Add defense
PATCH http://localhost:8010/juries/1
Content-Type: application/json

{
  "walletAddress": "0x714Ca817Ad92f9bae05DC18fA5312eB3F480cCCB"
}


### Add a vote
POST http://localhost:8010/juries/1/votes
Content-Type: application/json

{
  "walletAddress": "0x714Ca817Ad92f9bae05DC18fA5312eB3F480cCCB"
}


### Add a comment
POST http://localhost:8010/juries/1/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY3JlYXRlZEF0IjoiMjAyMy0wNC0xNVQwNToxMToxOC44MjBaIiwidXBkYXRlZEF0IjoiMjAyMy0wNC0xNVQwNToxMToxOC44MjBaIiwid2FsbGV0QWRkcmVzcyI6IjB4NzE0Q2E4MTdBZDkyZjliYWUwNURDMThmQTUzMTJlQjNGNDgwY0NDQiIsIm5hbWUiOiJtZ21nbWciLCJlbWFpbCI6ImNvYWxzcmJzN0BnbWFpbC5jb20iLCJ0d2l0dGVySGFuZGxlIjpudWxsLCJpYXQiOjE2ODE1MzcwMzYsImV4cCI6MTY4MTU0MDYzNn0.xVBfl03-PlW05EvF5KokfCkIpRSdemxXLZ7PRl6QPJs

{
  "content": "This is comment"
}


### Get comments
GET http://localhost:8010/juries/1/comments?page=1&size=100

### Delte a comment
GET http://localhost:8010/juries/1/comments

### Sign up
POST http://localhost:8010/users
Content-Type: application/json

{
  "name": "mgmgmg2",
  "email": "coalsrbs7@gmail.com",
  "walletAddress": "0x0000a817Ad92f9bae05DC18fA5312eB3F4800000"
}



### Get profile
GET http://localhost:8010/profile

### Get user
GET http://localhost:8010/users/0x512ADC0aB9B79dc842e19e91547da8dF874F5682

### Nonce
POST http://localhost:8010/nonce