### Health should return 200
GET http://localhost:8010/

### Non-exist api should return 404
GET http://localhost:8010/1ibac97h121?asd=12&nfkjd=4vnd

#{
#  "walletAddress": "0x0000a817Ad92f9bae05DC18fA5312eB3F4800000"
#}
### Auth(Login) should return 201
POST http://localhost:8010/auth
Content-Type: application/json

{
  "walletAddress": "0x0000a817Ad92f9bae05DC18fA5312eB3F4800000"
}



### Auth(Login) should return 404
POST http://localhost:8010/auth
Content-Type: application/json

{
  "walletAddress": "0xbadcoffeebadcoffeebadcoffeebadcoffeebadcoffee"
}

### Create a jury without token should return 401
POST http://localhost:8010/juries
Content-Type: application/json

{
  "plaintiffId": 1,
  "plaintiffTitle": "test1",
  "plaintiffContent": "test1test1",
  "defendantId": 2,
  "walletAddress": "0x714Ca817Ad92f9bae05DC18fA5312eB3F480cCCB",
  "signature": "askjdnjqwne12o"
}

### Create a jury should with wrong walletAddress & signature combination should return 403
POST http://localhost:8010/juries
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY3JlYXRlZEF0IjoiMjAyMy0wNC0xNVQwNToxMToxOC44MjBaIiwidXBkYXRlZEF0IjoiMjAyMy0wNC0xNVQwNToxMToxOC44MjBaIiwid2FsbGV0QWRkcmVzcyI6IjB4NzE0Q2E4MTdBZDkyZjliYWUwNURDMThmQTUzMTJlQjNGNDgwY0NDQiIsIm5hbWUiOiJtZ21nbWciLCJlbWFpbCI6ImNvYWxzcmJzN0BnbWFpbC5jb20iLCJ0d2l0dGVySGFuZGxlIjpudWxsLCJpYXQiOjE2ODE1NDE2ODQsImV4cCI6MTY4MTU0NTI4NH0.6agr1e-OZoQs8exrIqCTRj-zxjCaRX9jlkMHcdFmwBk

{
  "plaintiffId": 2,
  "plaintiffTitle": "test1",
  "plaintiffContent": "test1test1",
  "defendantId": 1,
  "walletAddress": "0x714Ca817Ad92f9bae05DC18fA5312eB3F480cCCB",
  "signature": "askjdnjqwne12o"
}

### Create a jury without token should return 401
POST http://localhost:8010/juries
Content-Type: application/json

{
  "plaintiffId": 1,
  "plaintiffTitle": "test1",
  "plaintiffContent": "test1test1",
  "defendantId": 2
}

### Get juries should return 200 / negative integer of page
GET http://localhost:8010/juries?page=-1&size=1

### Get juries should return 200 / negative integer of size
GET http://localhost:8010/juries?page=1&size=-10

### Get juries should return 200 / negative integer of page & size
GET http://localhost:8010/juries?page=-1&size=-10

### Get juries should return 200 / large number of page
GET http://localhost:8010/juries?page=99999&size=10

### Get juries should return 200 / large number of page & size
GET http://localhost:8010/juries?page=99999&size=99999

### Get a jury should return 200
GET http://localhost:8010/juries/2

### Get a jury should return 404
GET http://localhost:8010/juries/999999

### Get a jury should return 404
GET http://localhost:8010/juries/-1

### Add defense should return 200
PATCH http://localhost:8010/juries/8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY3JlYXRlZEF0IjoiMjAyMy0wNC0xNVQwNToxMToxOC44MjBaIiwidXBkYXRlZEF0IjoiMjAyMy0wNC0xNVQwNToxMToxOC44MjBaIiwid2FsbGV0QWRkcmVzcyI6IjB4NzE0Q2E4MTdBZDkyZjliYWUwNURDMThmQTUzMTJlQjNGNDgwY0NDQiIsIm5hbWUiOiJtZ21nbWciLCJlbWFpbCI6ImNvYWxzcmJzN0BnbWFpbC5jb20iLCJ0d2l0dGVySGFuZGxlIjpudWxsLCJpYXQiOjE2ODE1NDE2ODQsImV4cCI6MTY4MTU0NTI4NH0.6agr1e-OZoQs8exrIqCTRj-zxjCaRX9jlkMHcdFmwBk

{
  "walletAddress": "0x714Ca817Ad92f9bae05DC18fA5312eB3F480cCCB",
  "defendantTitle": "defense title",
  "defendantContent": "defense content",
  "defendantReferenceLink": ["asdasd", "nmknkjvn"]
}

### Add defense should return 403
PATCH http://localhost:8010/juries/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY3JlYXRlZEF0IjoiMjAyMy0wNC0xNVQwNToxMToxOC44MjBaIiwidXBkYXRlZEF0IjoiMjAyMy0wNC0xNVQwNToxMToxOC44MjBaIiwid2FsbGV0QWRkcmVzcyI6IjB4NzE0Q2E4MTdBZDkyZjliYWUwNURDMThmQTUzMTJlQjNGNDgwY0NDQiIsIm5hbWUiOiJtZ21nbWciLCJlbWFpbCI6ImNvYWxzcmJzN0BnbWFpbC5jb20iLCJ0d2l0dGVySGFuZGxlIjpudWxsLCJpYXQiOjE2ODE1NDE2ODQsImV4cCI6MTY4MTU0NTI4NH0.6agr1e-OZoQs8exrIqCTRj-zxjCaRX9jlkMHcdFmwBk

{
  "walletAddress": "0x714Ca817Ad92f9bae05DC18fA5312eB3F480cCCB",
  "defendantTitle": "defense title",
  "defendantContent": "defense content"
}

### Add a vote
POST http://localhost:8010/juries/1/votes
Content-Type: application/json

{
  "walletAddress": "0x714Ca817Ad92f9bae05DC18fA5312eB3F480cCCB"
}

### Add a comment should return 201
POST http://localhost:8010/juries/1/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY3JlYXRlZEF0IjoiMjAyMy0wNC0xNVQwNToxMToxOC44MjBaIiwidXBkYXRlZEF0IjoiMjAyMy0wNC0xNVQwNToxMToxOC44MjBaIiwid2FsbGV0QWRkcmVzcyI6IjB4NzE0Q2E4MTdBZDkyZjliYWUwNURDMThmQTUzMTJlQjNGNDgwY0NDQiIsIm5hbWUiOiJtZ21nbWciLCJlbWFpbCI6ImNvYWxzcmJzN0BnbWFpbC5jb20iLCJ0d2l0dGVySGFuZGxlIjpudWxsLCJpYXQiOjE2ODE1NDE2ODQsImV4cCI6MTY4MTU0NTI4NH0.6agr1e-OZoQs8exrIqCTRj-zxjCaRX9jlkMHcdFmwBk

{
  "content": "This is comment"
}

### Add a comment should return 401 without JWT
POST http://localhost:8010/juries/1/comments
Content-Type: application/json

{
  "content": "This is comment"
}

### Get comments should return 200 / negative integer of page
GET http://localhost:8010/juries/1/comments?page=-1&size=1

### Get comments should return 200 / negative integer of size
GET http://localhost:8010/juries/1/comments?page=1&size=-10

### Get comments should return 200 / negative integer of page & size
GET http://localhost:8010/juries/1/comments?page=-1&size=-10

### Get comments should return 200 / large number of page
GET http://localhost:8010/juries/1/comments?page=99999&size=10

### Get comments should return 200 / large number of page & size
GET http://localhost:8010/juries/1/comments?page=99999&size=99999

### Get comments should return 404
GET http://localhost:8010/juries/999999/comments?page=99999&size=99999

### Delte a comment should return 200
DELETE http://localhost:8010/juries/1/comments/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiY3JlYXRlZEF0IjoiMjAyMy0wNC0xNVQwNToxMTozOS45OTRaIiwidXBkYXRlZEF0IjoiMjAyMy0wNC0xNVQwNToxMTozOS45OTRaIiwid2FsbGV0QWRkcmVzcyI6IjB4MDAwMGE4MTdBZDkyZjliYWUwNURDMThmQTUzMTJlQjNGNDgwMDAwMCIsIm5hbWUiOiJtZ21nbWcyIiwiZW1haWwiOiJjb2Fsc3JiczdAZ21haWwuY29tIiwidHdpdHRlckhhbmRsZSI6bnVsbCwiaWF0IjoxNjgxNTQyMjU3LCJleHAiOjE2ODE1NDU4NTd9.2pZdDIAR9JhiQDX9WUsS7P186Xyrbk8QNXfV8YjamWM

### Delte a comment should return 404
DELETE http://localhost:8010/juries/1/comments/-1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY3JlYXRlZEF0IjoiMjAyMy0wNC0xNVQwNToxMToxOC44MjBaIiwidXBkYXRlZEF0IjoiMjAyMy0wNC0xNVQwNToxMToxOC44MjBaIiwid2FsbGV0QWRkcmVzcyI6IjB4NzE0Q2E4MTdBZDkyZjliYWUwNURDMThmQTUzMTJlQjNGNDgwY0NDQiIsIm5hbWUiOiJtZ21nbWciLCJlbWFpbCI6ImNvYWxzcmJzN0BnbWFpbC5jb20iLCJ0d2l0dGVySGFuZGxlIjpudWxsLCJpYXQiOjE2ODE1NDE2ODQsImV4cCI6MTY4MTU0NTI4NH0.6agr1e-OZoQs8exrIqCTRj-zxjCaRX9jlkMHcdFmwBk


### Delte a comment should return 404
DELETE http://localhost:8010/juries/1/comments/-1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY3JlYXRlZEF0IjoiMjAyMy0wNC0xNVQwNToxMToxOC44MjBaIiwidXBkYXRlZEF0IjoiMjAyMy0wNC0xNVQwNToxMToxOC44MjBaIiwid2FsbGV0QWRkcmVzcyI6IjB4NzE0Q2E4MTdBZDkyZjliYWUwNURDMThmQTUzMTJlQjNGNDgwY0NDQiIsIm5hbWUiOiJtZ21nbWciLCJlbWFpbCI6ImNvYWxzcmJzN0BnbWFpbC5jb20iLCJ0d2l0dGVySGFuZGxlIjpudWxsLCJpYXQiOjE2ODE1NDE2ODQsImV4cCI6MTY4MTU0NTI4NH0.6agr1e-OZoQs8exrIqCTRj-zxjCaRX9jlkMHcdFmwBk


### Delte a comment should return 404
DELETE http://localhost:8010/juries/99999/comments/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY3JlYXRlZEF0IjoiMjAyMy0wNC0xNVQwNToxMToxOC44MjBaIiwidXBkYXRlZEF0IjoiMjAyMy0wNC0xNVQwNToxMToxOC44MjBaIiwid2FsbGV0QWRkcmVzcyI6IjB4NzE0Q2E4MTdBZDkyZjliYWUwNURDMThmQTUzMTJlQjNGNDgwY0NDQiIsIm5hbWUiOiJtZ21nbWciLCJlbWFpbCI6ImNvYWxzcmJzN0BnbWFpbC5jb20iLCJ0d2l0dGVySGFuZGxlIjpudWxsLCJpYXQiOjE2ODE1NDE2ODQsImV4cCI6MTY4MTU0NTI4NH0.6agr1e-OZoQs8exrIqCTRj-zxjCaRX9jlkMHcdFmwBk


### Sign up
POST http://localhost:8010/users
Content-Type: application/json

{
  "name": "mgmgmg2",
  "email": "coalsrbs7@gmail.com",
  "walletAddress": "0x0000a817Ad92f9bae05DC18fA5312eB3F4800000",
  "signature": "129839ahsdasd"
}

### Get profile should return 200
GET http://localhost:8010/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY3JlYXRlZEF0IjoiMjAyMy0wNC0xNVQwNToxMToxOC44MjBaIiwidXBkYXRlZEF0IjoiMjAyMy0wNC0xNVQwNToxMToxOC44MjBaIiwid2FsbGV0QWRkcmVzcyI6IjB4NzE0Q2E4MTdBZDkyZjliYWUwNURDMThmQTUzMTJlQjNGNDgwY0NDQiIsIm5hbWUiOiJtZ21nbWciLCJlbWFpbCI6ImNvYWxzcmJzN0BnbWFpbC5jb20iLCJ0d2l0dGVySGFuZGxlIjpudWxsLCJpYXQiOjE2ODE1NDE2ODQsImV4cCI6MTY4MTU0NTI4NH0.6agr1e-OZoQs8exrIqCTRj-zxjCaRX9jlkMHcdFmwBk

### Get profile should return 401
GET http://localhost:8010/profile

### Get user should return 200
GET http://localhost:8010/users/0x512ADC0aB9B79dc842e19e91547da8dF874F5682
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY3JlYXRlZEF0IjoiMjAyMy0wNC0xNVQwNToxMToxOC44MjBaIiwidXBkYXRlZEF0IjoiMjAyMy0wNC0xNVQwNToxMToxOC44MjBaIiwid2FsbGV0QWRkcmVzcyI6IjB4NzE0Q2E4MTdBZDkyZjliYWUwNURDMThmQTUzMTJlQjNGNDgwY0NDQiIsIm5hbWUiOiJtZ21nbWciLCJlbWFpbCI6ImNvYWxzcmJzN0BnbWFpbC5jb20iLCJ0d2l0dGVySGFuZGxlIjpudWxsLCJpYXQiOjE2ODE1NDE2ODQsImV4cCI6MTY4MTU0NTI4NH0.6agr1e-OZoQs8exrIqCTRj-zxjCaRX9jlkMHcdFmwBk


### Get user should return 401
GET http://localhost:8010/users/0x512ADC0aB9B79dc842e19e91547da8dF874F5682


### Nonce should return 201
POST http://localhost:8010/nonce
Content-Type: application/json

{
  "walletAddress": "0x0000a817Ad92f9bae05DC18fA5312eB3F4800000"
}

